[package]
name = "stackdog"
version = "0.1.0"
authors = ["Vasili Pascal <info@try.direct>"]
edition = "2018"

#[package.metadata.docs.rs]
features = ["openssl", "rustls", "compress", "secure-cookies"]

[dependencies]
actix-web = { version = "3.0.0-beta.3", features=["rustls"] }
actix-rt = "2.1.0"
actix-service = "2.0.0"
actix-cors = "0.6.3"
actix-http = "2.1.0"
actix = "0.12"
log = "0.4.11"
env_logger = "0.9.0"
serde = "1.0.116"
bigdecimal = "0.3.0"
diesel_migrations = "1.4.0"
serde_derive = "1.0.116"
serde_json = "1.0.59"
dotenv = "0.15.0"
futures = "0.3.5"
failure = "0.1.8"
derive_more = "0.99.10"
jsonwebtoken = "8.0.1"
bcrypt = "0.10.0"
actix-tls = "3.0.0"
awc = { version = "2.0.0", default-features = false }
open-ssl = { package = "openssl", version = "0.10", optional = true }
rust-tls = { package = "rustls", version = "0.18.0", optional = true }

[features]
# openssl
openssl = ["actix-tls/openssl", "awc/openssl", "open-ssl"]
# rustls
rustls = ["actix-tls/rustls", "awc/rustls", "rust-tls"]
# content-encoding support
compress = ["actix-http/compress", "awc/compress"]
# sessions feature
secure-cookies = ["actix-http/secure-cookies"]

default = ["compress"]


[dependencies.chrono]
version = "0.4.15"
features = ["serde"]

[dependencies.uuid]
version = "0.8.1"
features = ["v4"]

[dependencies.diesel]
version = "1.4.6"
features = ["sqlite", "r2d2", "chrono", "numeric"]

[dev-dependencies.diesel]
version = "1.4.6"
features = ["r2d2", "chrono"]

