services:
  stackdog:
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    command: ["serve"]
    container_name: stackdog
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 5000
      DATABASE_URL: /data/stackdog.db
    ports:
      - "5000:5000"
    volumes:
      - stackdog-data:/data

  stackdog-ui:
    build:
      context: .
      dockerfile: docker/ui/Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:5000/api
        REACT_APP_WS_URL: ws://localhost:5000/ws
    container_name: stackdog-ui
    depends_on:
      - stackdog
    ports:
      - "3000:80"

volumes:
  stackdog-data:
