//! Security event types
//!
//! Defines the main SecurityEvent enum and related event types

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::events::syscall::SyscallEvent;

/// Main security event enum
///
/// All security-related events are represented as one of these variants
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum SecurityEvent {
    Syscall(SyscallEvent),
    Network(NetworkEvent),
    Container(ContainerEvent),
    Alert(AlertEvent),
}

impl SecurityEvent {
    /// Get the PID if this is a syscall event
    pub fn pid(&self) -> Option<u32> {
        match self {
            SecurityEvent::Syscall(e) => Some(e.pid),
            _ => None,
        }
    }
    
    /// Get the UID if this is a syscall event
    pub fn uid(&self) -> Option<u32> {
        match self {
            SecurityEvent::Syscall(e) => Some(e.uid),
            _ => None,
        }
    }
    
    /// Get the timestamp
    pub fn timestamp(&self) -> DateTime<Utc> {
        match self {
            SecurityEvent::Syscall(e) => e.timestamp,
            SecurityEvent::Network(e) => e.timestamp,
            SecurityEvent::Container(e) => e.timestamp,
            SecurityEvent::Alert(e) => e.timestamp,
        }
    }
}

// From implementations for converting to SecurityEvent
impl From<SyscallEvent> for SecurityEvent {
    fn from(event: SyscallEvent) -> Self {
        SecurityEvent::Syscall(event)
    }
}

impl From<NetworkEvent> for SecurityEvent {
    fn from(event: NetworkEvent) -> Self {
        SecurityEvent::Network(event)
    }
}

impl From<ContainerEvent> for SecurityEvent {
    fn from(event: ContainerEvent) -> Self {
        SecurityEvent::Container(event)
    }
}

impl From<AlertEvent> for SecurityEvent {
    fn from(event: AlertEvent) -> Self {
        SecurityEvent::Alert(event)
    }
}

/// Network-related security event
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct NetworkEvent {
    pub src_ip: String,
    pub dst_ip: String,
    pub src_port: u16,
    pub dst_port: u16,
    pub protocol: String,
    pub timestamp: DateTime<Utc>,
    pub container_id: Option<String>,
}

/// Container lifecycle event
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ContainerEvent {
    pub container_id: String,
    pub event_type: ContainerEventType,
    pub timestamp: DateTime<Utc>,
    pub details: Option<String>,
}

/// Types of container events
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum ContainerEventType {
    Start,
    Stop,
    Create,
    Destroy,
    Pause,
    Unpause,
}

/// Alert event generated by the security system
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AlertEvent {
    pub alert_type: AlertType,
    pub severity: AlertSeverity,
    pub message: String,
    pub timestamp: DateTime<Utc>,
    pub source_event_id: Option<String>,
}

/// Types of alerts
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum AlertType {
    ThreatDetected,
    AnomalyDetected,
    RuleViolation,
    QuarantineApplied,
}

/// Alert severity levels
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum AlertSeverity {
    Info,
    Low,
    Medium,
    High,
    Critical,
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_container_event_type_variants() {
        let _start = ContainerEventType::Start;
        let _stop = ContainerEventType::Stop;
    }
    
    #[test]
    fn test_alert_type_variants() {
        let _threat = AlertType::ThreatDetected;
        let _anomaly = AlertType::AnomalyDetected;
    }
    
    #[test]
    fn test_alert_severity_variants() {
        let _info = AlertSeverity::Info;
        let _critical = AlertSeverity::Critical;
    }
    
    #[test]
    fn test_security_event_from_syscall() {
        let syscall_event = SyscallEvent::new(
            1234,
            1000,
            crate::events::syscall::SyscallType::Execve,
            Utc::now(),
        );
        
        let security_event: SecurityEvent = syscall_event.into();
        
        match security_event {
            SecurityEvent::Syscall(_) => {},
            _ => panic!("Expected Syscall variant"),
        }
    }
}
