[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
loglevel=info

[program:nextjs]
command=node /app/server.js
environment=NODE_ENV=production,PORT=3000,HOSTNAME=127.0.0.1
user=app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
